version: '3'
services:
  neo4j:
    image: neo4j:4.4.9
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*,gds.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*,algo.*,gds.*
      - NEO4J_dbms.security.procedures.allowlist=gds.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_AUTH=neo4j/fleet
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/plugin:/plugins
      - ./neo4j/logs:/logs
      - ./neo4j/import:/import
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
  neoapi:
    build: ..
    ports:
      - "5000:5000"
    container_name: neoapi
volumes:
  grafana-data:


